server:
  port: 8080

spring:
  liquibase:
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online-wallet-app
    username: user
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: none

#jwt:
#  secret: yourSecretKey
#  lifetime: 30

#logging:
#  file:
#    path: ./
#    name: cloudStorageApp
